#!/usr/bin/env python3
"""Build deterministic profile presentation fragments from research metrics."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "data" / "research-metrics.json"
CONFIG = ROOT / "config" / "site.json"
OUTPUT = ROOT / "includes" / "profile-sidebar.html"


def load_metrics() -> dict:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    required = {"updated_at", "orcid", "public_orcid_works", "openalex"}
    missing = required - data.keys()
    if missing:
        raise ValueError(f"research-metrics.json missing fields: {sorted(missing)}")
    return data


def load_identity() -> dict:
    data = json.loads(CONFIG.read_text(encoding="utf-8"))
    return data["identity"]


def display_metric(value: object) -> str:
    """Render zero or unavailable metric values as a short hyphen."""
    if value is None:
        return "-"
    if isinstance(value, (int, float)) and not isinstance(value, bool) and value == 0:
        return "-"
    text = str(value).strip()
    return "-" if text in {"", "0", "0.0"} else text


def render(data: dict, identity: dict) -> str:
    oa = data["openalex"]
    metrics = [
        ("Citations", oa.get("cited_by_count", 0)),
        ("h-index", oa.get("h_index", 0)),
        ("i10-index", oa.get("i10_index", 0)),
        ("ORCID works", data["public_orcid_works"]),
        ("OpenAlex works", oa.get("works_count", 0)),
    ]

    metric_rows = "\n".join(
        '<div class="qs-sidebar-metric-row">'
        f'<span>{html.escape(label)}</span>'
        f'<strong>{html.escape(display_metric(value))}</strong>'
        '</div>'
        for label, value in metrics
    )

    name = html.escape(identity["name"])
    orcid = html.escape(identity["orcid"], quote=True)
    scholar = html.escape(identity["google_scholar"], quote=True)
    github = html.escape(identity["github"], quote=True)
    linkedin = html.escape(identity["linkedin"], quote=True)

    return f'''<!-- Generated by scripts/build_home.py. Do not edit manually. -->
<aside class="qs-profile-sidebar" aria-label="Research profile">
  <div class="qs-sidebar-inner">
    <div class="qs-sidebar-portrait">
      <img src="/images/profile.png" alt="Portrait of {name}">
    </div>
    <p class="qs-sidebar-name">{name}</p>
    <p class="qs-sidebar-role">Marine Quantitative Ecologist<br>Fisheries Scientist</p>
    <div class="qs-sidebar-context"><i class="bi bi-geo-alt-fill" aria-hidden="true"></i><span>Peru · Humboldt Current</span></div>
    <div class="qs-sidebar-context"><i class="bi bi-water" aria-hidden="true"></i><span>Pelagic fisheries · Statistical ecology</span></div>
    <p class="qs-sidebar-section-label">Research profiles</p>
    <nav class="qs-sidebar-links" aria-label="Research profiles">
      <a href="https://orcid.org/{orcid}"><i class="bi bi-person-badge" aria-hidden="true"></i><span>ORCID</span></a>
      <a href="{scholar}"><i class="bi bi-mortarboard-fill" aria-hidden="true"></i><span>Google Scholar</span></a>
      <a href="{github}"><i class="bi bi-github" aria-hidden="true"></i><span>GitHub</span></a>
      <a href="{linkedin}"><i class="bi bi-linkedin" aria-hidden="true"></i><span>LinkedIn</span></a>
    </nav>
    <p class="qs-sidebar-section-label">Research metrics</p>
    <div class="qs-sidebar-metrics-list" aria-label="Research metrics">
      {metric_rows}
    </div>
    <p class="qs-sidebar-metrics-note">OpenAlex metrics · ORCID works. Google Scholar is linked above for profile discovery.</p>
  </div>
</aside>
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if the generated profile sidebar is stale.")
    args = parser.parse_args()

    expected = render(load_metrics(), load_identity())

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != expected:
            raise SystemExit("includes/profile-sidebar.html is stale; run python scripts/build_home.py")
        print("Profile sidebar metrics fragment is current.")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
