#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "assets" / "data" / "teaching.json"
REGISTRY = ROOT / "teaching" / "registry.json"
TARGET = ROOT / "teaching" / "_generated.md"


def load_json(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError(f"{path} must contain a JSON object")
    return payload


def badge(label: str, value: str, tone: str = "neutral") -> str:
    body = (
        f'<span class="qs-badge-label">{html.escape(label)}</span>'
        f'<span class="qs-badge-value">{html.escape(value)}</span>'
    )
    return f'<span class="qs-badge qs-badge-{tone}">{body}</span>'


def display_name(name: str) -> str:
    if name == ".template-training":
        return "SCIENTIFIC TRAINING TEMPLATE"
    cleaned = re.sub(r"-training$", "", name, flags=re.IGNORECASE)
    cleaned = cleaned.replace("_", " ").replace("-", " ")
    cleaned = " ".join(cleaned.split())
    if cleaned.casefold() == "git github":
        return "GIT & GITHUB"
    return cleaned.upper()


def compact_type(category: str) -> str:
    if "template" in category.casefold():
        return "Template"
    if "course" in category.casefold():
        return "Course"
    return "Resource"


def compact_status(maturity: str) -> str:
    low = maturity.casefold()
    if "active" in low:
        return "Active"
    if "reusable" in low:
        return "Reusable"
    return maturity or "Development"


def render_item(item: dict) -> str:
    name = str(item.get("name") or "Unnamed resource").strip()
    category = str(item.get("category") or "Teaching resource").strip()
    maturity = str(item.get("maturity") or "Development").strip()
    language = str(item.get("language") or "-").strip()
    summary = str(item.get("summary") or item.get("description") or "").strip()
    site_path = str(item.get("site_path") or "").strip()
    repo_url = str(item.get("html_url") or "").strip()
    display = display_name(name)
    target = site_path or repo_url

    badges = [
        badge("Type", compact_type(category), "neutral"),
        badge("Status", compact_status(maturity), "green"),
        badge("Language", language if language and language != "-" else "Mixed", "blue"),
    ]

    title = html.escape(display)
    if target:
        title = f'<a class="qs-teaching-title-link" href="{html.escape(target, quote=True)}">{title}</a>'

    links: list[str] = []
    if site_path:
        links.append(f'<a href="{html.escape(site_path, quote=True)}">Teaching page</a>')
    if repo_url:
        links.append(f'<a href="{html.escape(repo_url, quote=True)}">Repository</a>')

    parts = [
        '<article class="qs-teaching-entry">',
        f'<h3 class="qs-teaching-title">{title}</h3>',
    ]
    if summary:
        parts.append(f'<p class="qs-teaching-summary">{html.escape(summary)}</p>')
    parts.append(f'<div class="qs-badge-row qs-publication-badges">{"".join(badges)}</div>')
    if links:
        parts.append(f'<p class="qs-teaching-links">{" <span aria-hidden="true">|</span> ".join(links)}</p>')
    parts.append('</article>')
    return "".join(parts)


def render() -> str:
    data = load_json(DATA)
    registry = load_json(REGISTRY)
    teaching = data.get("teaching")
    infrastructure = data.get("infrastructure")
    if not isinstance(teaching, list) or not isinstance(infrastructure, list):
        raise RuntimeError("assets/data/teaching.json must contain teaching and infrastructure lists")

    expected_teaching = {str(item.get("repository") or "").strip() for item in registry.get("published", []) if str(item.get("repository") or "").strip()}
    found_teaching = {str(item.get("full_name") or "").strip() for item in teaching}
    if found_teaching != expected_teaching:
        raise RuntimeError(f"Teaching mirror does not match registry; missing={sorted(expected_teaching - found_teaching)}, unexpected={sorted(found_teaching - expected_teaching)}")

    expected_infra = {str(item.get("repository") or "").strip() for item in registry.get("infrastructure", []) if str(item.get("repository") or "").strip()}
    found_infra = {str(item.get("full_name") or "").strip() for item in infrastructure}
    if found_infra != expected_infra:
        raise RuntimeError(f"Teaching infrastructure mirror does not match registry; missing={sorted(expected_infra - found_infra)}, unexpected={sorted(found_infra - expected_infra)}")

    lines = ["<!-- Generated by scripts/build_teaching.py; do not edit manually. -->", ""]
    if teaching:
        lines += ["## Courses and training {#courses}", "", "```{=html}"]
        for item in sorted(teaching, key=lambda x: str(x.get("name") or "").casefold()):
            lines.append(render_item(item))
        lines += ["```", ""]
    if infrastructure:
        lines += ["## Teaching infrastructure {#infrastructure}", "", "```{=html}"]
        for item in sorted(infrastructure, key=lambda x: str(x.get("name") or "").casefold()):
            lines.append(render_item(item))
        lines += ["```", ""]
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != expected:
            raise SystemExit("teaching/_generated.md is stale; run python scripts/build_teaching.py")
        print("Teaching fragment is synchronized.")
        return
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
