#!/usr/bin/env python3
"""Build deterministic About-page and profile fragments from canonical site data."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
METRICS_SOURCE = ROOT / "assets" / "data" / "research-metrics.json"
SCHOLARLY_GRAPH_SOURCE = ROOT / "assets" / "data" / "scholarly-graph.json"
CONFIG = ROOT / "config" / "site.json"
SIDEBAR_OUTPUT = ROOT / "includes" / "profile-sidebar.html"
SELECTED_OUTPUT = ROOT / "includes" / "about-selected.html"


def load_json(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path.relative_to(ROOT)} must contain a JSON object")
    return data


def load_metrics() -> dict:
    data = load_json(METRICS_SOURCE)
    required = {"updated_at", "orcid", "public_orcid_works", "openalex"}
    missing = required - data.keys()
    if missing:
        raise ValueError(f"research-metrics.json missing fields: {sorted(missing)}")
    return data


def load_identity() -> dict:
    return load_json(CONFIG)["identity"]


def metric_available(value: object) -> bool:
    if value is None or isinstance(value, bool):
        return False
    if isinstance(value, (int, float)):
        return value > 0
    text = str(value).strip()
    if not text:
        return False
    try:
        return float(text) > 0
    except ValueError:
        return True


def display_metric(value: object) -> str:
    return str(value).strip()


def render_sidebar(data: dict, identity: dict) -> str:
    oa = data["openalex"]
    metrics = [
        ("Citations", oa.get("cited_by_count")),
        ("h-index", oa.get("h_index")),
        ("i10-index", oa.get("i10_index")),
        ("ORCID works", data.get("public_orcid_works")),
        ("OpenAlex works", oa.get("works_count")),
    ]
    metrics = [(label, value) for label, value in metrics if metric_available(value)]

    metric_rows = "\n".join(
        '<div class="qs-sidebar-metric-row">'
        f'<span>{html.escape(label)}</span>'
        f'<span class="qs-sidebar-metric-value">{html.escape(display_metric(value))}</span>'
        '</div>'
        for label, value in metrics
    )
    metrics_block = ""
    if metric_rows:
        metrics_block = f"""    <p class="qs-sidebar-section-label">Research metrics</p>
    <div class="qs-sidebar-metrics-list" aria-label="Research metrics">
      {metric_rows}
    </div>
    <p class="qs-sidebar-metrics-note">Public ORCID and OpenAlex records.</p>
"""

    name = html.escape(identity["name"])
    orcid = html.escape(identity["orcid"], quote=True)
    scholar = html.escape(identity["google_scholar"], quote=True)
    github = html.escape(identity["github"], quote=True)
    linkedin = html.escape(identity["linkedin"], quote=True)

    return f"""<!-- Generated by scripts/build_home.py. Do not edit manually. -->
<aside class="qs-profile-sidebar" aria-label="Research profile">
  <div class="qs-sidebar-inner">
    <div class="qs-sidebar-portrait">
      <img src="/images/profile.png" alt="Portrait of {name}">
    </div>
    <p class="qs-sidebar-name">{name}</p>
    <p class="qs-sidebar-role">Marine Quantitative Ecologist<br>Fisheries Scientist</p>
    <div class="qs-sidebar-context qs-sidebar-affiliation"><i class="bi bi-building" aria-hidden="true"></i><span>Instituto del Mar del Perú (IMARPE)</span></div>
    <div class="qs-sidebar-context"><i class="bi bi-geo-alt-fill" aria-hidden="true"></i><span>Peru · Humboldt Current</span></div>
    <div class="qs-sidebar-context"><i class="bi bi-water" aria-hidden="true"></i><span>Pelagic fisheries · Statistical ecology</span></div>
    <p class="qs-sidebar-section-label">Research profiles</p>
    <nav class="qs-sidebar-links" aria-label="Research profiles">
      <a href="https://orcid.org/{orcid}"><i class="bi bi-person-badge" aria-hidden="true"></i><span>ORCID</span></a>
      <a href="{scholar}"><i class="bi bi-mortarboard-fill" aria-hidden="true"></i><span>Google Scholar</span></a>
      <a href="{github}"><i class="bi bi-github" aria-hidden="true"></i><span>GitHub</span></a>
      <a href="{linkedin}"><i class="bi bi-linkedin" aria-hidden="true"></i><span>LinkedIn</span></a>
    </nav>
{metrics_block}  </div>
</aside>
"""


def render_selected_card(kind: str, title: str, url: str, summary: str) -> str:
    return (
        '<article class="qs-project-tile">'
        '<div class="qs-project-body">'
        f'<span class="qs-project-type">{html.escape(kind.upper())}</span>'
        f'<h3><a href="{html.escape(url, quote=True)}">{html.escape(title)}</a></h3>'
        f'<p class="qs-project-card-summary">{html.escape(summary)}</p>'
        '</div>'
        '</article>'
    )


def selected_summary(node: dict) -> str:
    summary = str(node.get("summary") or "").strip()
    if summary:
        return summary
    kind = str(node.get("kind") or "")
    if kind == "Publication":
        return " · ".join(
            part for part in (
                str(node.get("venue") or "").strip(),
                str(node.get("year") or "").strip(),
            ) if part
        )
    if kind in {"Talk", "Poster"}:
        return str(node.get("event") or "").strip()
    if kind == "Software":
        return " · ".join(
            part for part in (
                str(node.get("language") or "").strip(),
                str(node.get("status") or "").strip(),
            ) if part
        )
    return str(node.get("status") or "").strip()


def render_selected_research() -> str:
    graph = load_json(SCHOLARLY_GRAPH_SOURCE)
    if graph.get("schema_version") != 1 or graph.get("public_only") is not True:
        raise ValueError("assets/data/scholarly-graph.json must be a public Phase 7 graph")
    nodes = {
        str(item.get("id") or ""): item
        for item in graph.get("nodes") or []
        if isinstance(item, dict) and str(item.get("id") or "")
    }
    featured = graph.get("featured") or {}
    if not isinstance(featured, dict):
        raise ValueError("Scholarly graph featured selection must be an object")

    order = (("project", "Project"), ("paper", "Paper"), ("software", "Software"), ("talk", "Talk"))
    cards: list[str] = []
    for key, label in order:
        node_id = str(featured.get(key) or "").strip()
        if not node_id:
            continue
        node = nodes.get(node_id)
        if node is None:
            raise ValueError(f"Featured graph node is missing: {node_id}")
        cards.append(
            render_selected_card(
                label,
                str(node.get("title") or ""),
                str(node.get("canonical_url") or ""),
                selected_summary(node),
            )
        )

    return (
        '<!-- Generated by scripts/build_home.py from assets/data/scholarly-graph.json. Do not edit manually. -->\n'
        '<div class="qs-selected-grid">\n'
        + "\n".join(cards)
        + '\n</div>\n'
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated About/profile fragments are stale.")
    args = parser.parse_args()

    expected_sidebar = render_sidebar(load_metrics(), load_identity())
    expected_selected = render_selected_research()

    if args.check:
        checks = (
            (SIDEBAR_OUTPUT, expected_sidebar),
            (SELECTED_OUTPUT, expected_selected),
        )
        stale = [
            path.relative_to(ROOT)
            for path, expected in checks
            if (path.read_text(encoding="utf-8") if path.exists() else "") != expected
        ]
        if stale:
            raise SystemExit(
                f"Generated About/profile fragments are stale: {', '.join(map(str, stale))}; "
                "run python scripts/build_scholarly_graph.py && python scripts/build_home.py"
            )
        print("About and profile fragments are current and derive Selected research from the scholarly graph.")
        return

    SIDEBAR_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    SIDEBAR_OUTPUT.write_text(expected_sidebar, encoding="utf-8")
    SELECTED_OUTPUT.write_text(expected_selected, encoding="utf-8")
    print(f"Generated {SIDEBAR_OUTPUT.relative_to(ROOT)}")
    print(f"Generated {SELECTED_OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
