#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "data" / "registry.json"
TARGET = ROOT / "data" / "_generated.md"

REQUIRED_FIELDS = {
    "id", "name", "provider", "category", "access", "access_group",
    "coverage", "formats", "description", "use_case", "terms", "url",
    "recommended",
}
ACCESS_GROUPS = {"open", "registered", "licensed_or_restricted"}


def load_registry() -> dict:
    payload = json.loads(REGISTRY.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError("data/registry.json must contain a JSON object")
    if payload.get("schema_version") != 1:
        raise RuntimeError("Unsupported data registry schema_version")
    categories = payload.get("categories")
    resources = payload.get("resources")
    if not isinstance(categories, list) or not categories:
        raise RuntimeError("data registry categories must be a non-empty list")
    if not isinstance(resources, list) or not resources:
        raise RuntimeError("data registry resources must be a non-empty list")
    return payload


def validate(payload: dict) -> None:
    categories = payload["categories"]
    ids: set[str] = set()
    for item in payload["resources"]:
        if not isinstance(item, dict):
            raise RuntimeError("Every data resource must be a JSON object")
        missing = sorted(REQUIRED_FIELDS - set(item))
        if missing:
            raise RuntimeError(f"Data resource is missing required fields: {missing}")
        resource_id = str(item["id"]).strip()
        if not resource_id:
            raise RuntimeError("Data resource id cannot be empty")
        if resource_id in ids:
            raise RuntimeError(f"Duplicate data resource id: {resource_id}")
        ids.add(resource_id)
        category = str(item["category"]).strip()
        if category not in categories:
            raise RuntimeError(f"Unknown data category for {resource_id}: {category}")
        access_group = str(item["access_group"]).strip()
        if access_group not in ACCESS_GROUPS:
            raise RuntimeError(f"Invalid access_group for {resource_id}: {access_group}")
        parsed = urlparse(str(item["url"]).strip())
        if parsed.scheme != "https" or not parsed.netloc:
            raise RuntimeError(f"Authoritative URL must be absolute HTTPS: {resource_id}")
        if not isinstance(item["recommended"], bool):
            raise RuntimeError(f"recommended must be boolean: {resource_id}")


def cell(value: object) -> str:
    return " ".join(str(value).split()).replace("|", "\\|")


def render(payload: dict) -> str:
    validate(payload)
    resources = payload["resources"]
    categories = payload["categories"]
    reviewed_on = cell(payload.get("reviewed_on") or "")
    counts = Counter(str(item["access_group"]) for item in resources)
    recommended = [item for item in resources if item["recommended"]]

    lines = [
        "<!-- Generated by scripts/build_data_resources.py; do not edit manually. -->",
        "",
        "::: {.callout-note}",
        "## External-source policy",
        "",
        "**None of the datasets listed here are produced or owned by Elmer Quispe-Salazar.** "
        "This is a curated discovery directory for students and collaborators. Data remain with "
        "their original providers; users must verify the current licence, citation, access "
        "conditions, caveats, and version before use.",
        ":::",
        "",
        f"**{len(resources)} external sources · {len(categories)} domains · "
        f"{counts['open']} open · {counts['registered']} registration-based · "
        f"{counts['licensed_or_restricted']} licensed/restricted**",
        "",
    ]
    if reviewed_on:
        lines += [f"Catalogue last reviewed: **{reviewed_on}**.", ""]

    lines += [
        "## Recommended starting points",
        "",
        "These are practical first choices for routine fisheries, marine ecology, oceanography, spatial analysis, and teaching workflows.",
        "",
    ]
    for item in recommended:
        lines.append(f"- **[{cell(item['name'])}]({item['url']})** — {cell(item['use_case'])}")
    lines += [
        "",
        "## Access legend",
        "",
        "- **Open** — no paid licence is required, although attribution or dataset-specific terms may still apply.",
        "- **Registration-based** — an account, token, licence acceptance, or registered download workflow is required.",
        "- **Licensed/restricted** — academic approval, institutional permission, or a commercial agreement is required.",
        "",
    ]

    for category in categories:
        group = [item for item in resources if item["category"] == category]
        if not group:
            continue
        lines += [
            f"## {category}",
            "",
            "| Source | Access | Coverage | Formats | Useful for |",
            "|---|---|---|---|---|",
        ]
        for item in group:
            source = f"[{cell(item['name'])}]({item['url']})"
            lines.append(
                f"| {source} | {cell(item['access'])} | {cell(item['coverage'])} | "
                f"{cell(item['formats'])} | {cell(item['use_case'])} |"
            )
        lines.append("")

    lines += [
        "## Use in teaching and collaboration",
        "",
        "For reproducible work, record the provider, dataset or product name, version or access date, spatial and temporal subset, licence, citation, and the exact download or API query used. Do not upload restricted or licensed source data to public repositories unless the provider explicitly permits redistribution.",
        "",
        "Detailed access and licence notes are retained in `data/registry.json`; always treat the provider's current documentation as authoritative.",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = load_registry()
    expected = render(payload)
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != expected:
            raise SystemExit("data/_generated.md is stale; run python scripts/build_data_resources.py")
        print(f"Data catalogue synchronized: {len(payload['resources'])} external sources.")
        return
    TARGET.write_text(expected, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
