#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "blog" / "registry.json"
TARGET = ROOT / "blog" / "_generated.md"


def load_registry() -> dict:
    payload = json.loads(REGISTRY.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError("blog/registry.json must contain a JSON object")
    posts = payload.get("posts")
    if not isinstance(posts, list):
        raise RuntimeError("blog/registry.json must contain a posts list")
    return payload


def validate_post(post: dict) -> None:
    required = ("slug", "title", "date", "route", "topic", "level", "status", "excerpt")
    missing = [key for key in required if not str(post.get(key) or "").strip()]
    if missing:
        raise RuntimeError(f"Blog post is missing required fields: {missing}")

    try:
        date.fromisoformat(str(post["date"]))
    except ValueError as exc:
        raise RuntimeError(f"Invalid blog date for {post['slug']}: {post['date']}") from exc

    route = str(post["route"])
    if not route.startswith("/blog/") or not route.endswith("/"):
        raise RuntimeError(f"Blog route must be /blog/<slug>/: {route}")

    relation = post.get("class_relation")
    if not isinstance(relation, dict):
        raise RuntimeError(f"Blog post {post['slug']} must define class_relation")

    legacy_exception = bool(post.get("legacy_exception", False))
    if not legacy_exception:
        if relation.get("status") != "linked":
            raise RuntimeError(
                f"New blog post {post['slug']} must be linked to a published class"
            )
        if not str(relation.get("teaching_path") or "").strip():
            raise RuntimeError(
                f"New blog post {post['slug']} must provide class_relation.teaching_path"
            )


def render_post(post: dict) -> list[str]:
    relation = post["class_relation"]
    route = str(post["route"])
    lines = [
        f"### [{post['title']}]({route})",
        "",
        f"**{post['date']} · {post['topic']} · {post['level']}**",
        "",
        str(post["excerpt"]).strip(),
        "",
    ]

    if relation.get("status") == "linked":
        teaching_path = str(relation.get("teaching_path") or "").strip()
        lines += [f"**Continue with the class:** [Open the structured class]({teaching_path})", ""]
    else:
        note = str(relation.get("note") or "Class pathway not yet published.").strip()
        lines += [f"**Class pathway:** {note}", ""]

    social_links = post.get("social_links") or []
    if social_links:
        links = []
        for item in social_links:
            if not isinstance(item, dict):
                continue
            platform = str(item.get("platform") or "Social post").strip()
            url = str(item.get("url") or "").strip()
            if url:
                links.append(f"[{platform}]({url})")
        if links:
            lines += ["**Social entry points:** " + " · ".join(links), ""]

    return lines


def render() -> str:
    payload = load_registry()
    posts = payload["posts"]
    slugs = set()
    routes = set()
    for post in posts:
        if not isinstance(post, dict):
            raise RuntimeError("Every blog post record must be a JSON object")
        validate_post(post)
        slug = str(post["slug"])
        route = str(post["route"])
        if slug in slugs:
            raise RuntimeError(f"Duplicate blog slug: {slug}")
        if route in routes:
            raise RuntimeError(f"Duplicate blog route: {route}")
        slugs.add(slug)
        routes.add(route)

    linked = sum(1 for post in posts if post["class_relation"].get("status") == "linked")
    legacy = sum(1 for post in posts if bool(post.get("legacy_exception", False)))

    lines = [
        "<!-- Generated by scripts/build_blog.py; do not edit manually. -->",
        "",
        "::: {.callout-tip}",
        "## Communication pathway",
        "",
        "**Reader journey:** Social post → Blog → Class  ",
        "**Content production:** Class → Blog → Social post",
        "",
        "A blog article explains one teaching theme in enough depth to be useful on its own, while the class contains the structured learning sequence, exercises, code, and supporting material.",
        ":::",
        "",
        f"**{len(posts)} extended article{'s' if len(posts) != 1 else ''} · {linked} linked to a published class · {legacy} legacy migration exception{'s' if legacy != 1 else ''}**",
        "",
        "## Extended articles",
        "",
    ]

    for post in sorted(posts, key=lambda item: str(item["date"]), reverse=True):
        lines += render_post(post)

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != expected:
            raise SystemExit("blog/_generated.md is stale; run python scripts/build_blog.py")
        print("Blog fragment is synchronized.")
        return

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
