#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "assets" / "data" / "software.json"
REGISTRY = ROOT / "software" / "registry.json"
TARGET = ROOT / "software" / "_generated.md"


def load_json(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError(f"{path} must contain a JSON object")
    return payload


def render() -> str:
    data = load_json(DATA)
    registry = load_json(REGISTRY)

    items = data.get("software")
    if not isinstance(items, list):
        raise RuntimeError("assets/data/software.json must contain a software list")

    expected = {
        str(item.get("repository") or "").strip()
        for item in registry.get("published", [])
        if str(item.get("repository") or "").strip()
    }
    found = {str(item.get("full_name") or "").strip() for item in items}
    if found != expected:
        missing = sorted(expected - found)
        unexpected = sorted(found - expected)
        raise RuntimeError(
            f"Software mirror does not match registry; missing={missing}, unexpected={unexpected}"
        )

    groups = [
        ("R package", "Scientific packages"),
        ("Experimental application", "Experimental applications"),
    ]

    lines = [
        "<!-- Generated by scripts/build_software.py; do not edit manually. -->",
        "",
    ]

    for category, heading in groups:
        group = [item for item in items if item.get("category") == category]
        if not group:
            continue
        lines += [f"## {heading}", ""]
        for item in sorted(group, key=lambda x: str(x.get("name") or "").casefold()):
            name = str(item.get("name") or "Unnamed software")
            maturity = str(item.get("maturity") or "Development")
            language = str(item.get("language") or "—")
            summary = str(item.get("summary") or item.get("description") or "").strip()
            site_path = str(item.get("site_path") or "").strip()
            repo_url = str(item.get("html_url") or "").strip()

            lines += [
                f"### `{name}`",
                "",
                f"**{category} · {maturity} · {language}**",
                "",
            ]
            if summary:
                lines += [summary, ""]
            links = []
            if site_path:
                links.append(f"[Project page]({site_path})")
            if repo_url:
                links.append(f"[Repository]({repo_url})")
            if links:
                lines += [" · ".join(links), ""]

    incubating = registry.get("incubating") or []
    concepts = registry.get("concepts") or []
    if incubating or concepts:
        lines += [
            "## Incubating and concept-stage work",
            "",
            "These records are preserved for continuity but are not presented as released or validated scientific software.",
            "",
        ]
        for item in incubating:
            full_name = str(item.get("repository") or "")
            name = full_name.split("/", 1)[-1] if full_name else "Unnamed repository"
            site_path = str(item.get("site_path") or "").strip()
            reason = str(item.get("reason") or "").strip()
            label = f"[`{name}`]({site_path})" if site_path else f"`{name}`"
            lines.append(f"- {label} — {reason}")
        for item in concepts:
            name = str(item.get("name") or "Unnamed concept")
            site_path = str(item.get("site_path") or "").strip()
            reason = str(item.get("reason") or "").strip()
            label = f"[{name}]({site_path})" if site_path else name
            lines.append(f"- {label} — {reason}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != expected:
            raise SystemExit(
                "software/_generated.md is stale; run python scripts/build_software.py"
            )
        print("Software fragment is synchronized.")
        return

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
