#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "assets" / "data" / "teaching.json"
REGISTRY = ROOT / "teaching" / "registry.json"
TARGET = ROOT / "teaching" / "_generated.md"


def load_json(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise RuntimeError(f"{path} must contain a JSON object")
    return payload


def render_item(item: dict, page_label: str) -> list[str]:
    name = str(item.get("name") or "Unnamed resource")
    category = str(item.get("category") or "Teaching resource")
    maturity = str(item.get("maturity") or "Development")
    language = str(item.get("language") or "—")
    summary = str(item.get("summary") or item.get("description") or "").strip()
    site_path = str(item.get("site_path") or "").strip()
    repo_url = str(item.get("html_url") or "").strip()

    display = "Scientific Training Template" if name == ".template-training" else name
    lines = [
        f"### {display}",
        "",
        f"**{category} · {maturity} · {language}**",
        "",
    ]
    if summary:
        lines += [summary, ""]
    links = []
    if site_path:
        links.append(f"[{page_label}]({site_path})")
    if repo_url:
        links.append(f"[Repository]({repo_url})")
    if links:
        lines += [" · ".join(links), ""]
    return lines


def render() -> str:
    data = load_json(DATA)
    registry = load_json(REGISTRY)

    teaching = data.get("teaching")
    infrastructure = data.get("infrastructure")
    if not isinstance(teaching, list) or not isinstance(infrastructure, list):
        raise RuntimeError(
            "assets/data/teaching.json must contain teaching and infrastructure lists"
        )

    expected_teaching = {
        str(item.get("repository") or "").strip()
        for item in registry.get("published", [])
        if str(item.get("repository") or "").strip()
    }
    found_teaching = {str(item.get("full_name") or "").strip() for item in teaching}
    if found_teaching != expected_teaching:
        raise RuntimeError(
            "Teaching mirror does not match registry; "
            f"missing={sorted(expected_teaching - found_teaching)}, "
            f"unexpected={sorted(found_teaching - expected_teaching)}"
        )

    expected_infra = {
        str(item.get("repository") or "").strip()
        for item in registry.get("infrastructure", [])
        if str(item.get("repository") or "").strip()
    }
    found_infra = {str(item.get("full_name") or "").strip() for item in infrastructure}
    if found_infra != expected_infra:
        raise RuntimeError(
            "Teaching infrastructure mirror does not match registry; "
            f"missing={sorted(expected_infra - found_infra)}, "
            f"unexpected={sorted(found_infra - expected_infra)}"
        )

    lines = [
        "<!-- Generated by scripts/build_teaching.py; do not edit manually. -->",
        "",
    ]

    if teaching:
        lines += ["## Courses and training", ""]
        for item in sorted(teaching, key=lambda x: str(x.get("name") or "").casefold()):
            lines += render_item(item, "Teaching page")

    if infrastructure:
        lines += ["## Teaching infrastructure", ""]
        for item in sorted(
            infrastructure, key=lambda x: str(x.get("name") or "").casefold()
        ):
            lines += render_item(item, "Resource page")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render()
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != expected:
            raise SystemExit(
                "teaching/_generated.md is stale; run python scripts/build_teaching.py"
            )
        print("Teaching fragment is synchronized.")
        return

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
